version: '3.7'

networks:
    greenmap:
        driver: bridge

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        environment:
            - MONGO_USER=${MONGO_USER}
            - MONGO_PASSWORD=${MONGO_PASSWORD}
            - MONGO_CONNECTION_STRING=${MONGO_CONNECTION_STRING}
            - MONGO_DB=${MONGO_DB}
            - MONGO_LOCATION="col_locations"
        restart: unless-stopped
        expose:
            - 8080
        networks:
            - greenmap
        depends_on: 
            - mongo

    mongo:
        image: mongo
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
            - MONGO_INITDB_DATABASE=greenmap
        networks:
            - greenmap
    mongo-express:
        image: mongo-express:0.54
        ports:
            - "8081:8081"
        environment:
            - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
            - ME_CONFIG_BASICAUTH_USERNAME=dev
            - ME_CONFIG_BASICAUTH_PASSWORD=dev
            - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
            - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
        links:
            - "mongo"
        networks:
            - greenmap
